/*
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * represents a face landmark point.
 */
@ApiModel(description = "represents a face landmark point.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-02T11:12:16.872Z")
public class Point {
  @SerializedName("x")
  private Double x = null;

  @SerializedName("y")
  private Double y = null;

  @SerializedName("type")
  private Integer type = null;

  @SerializedName("name")
  private String name = null;

  public Point x(Double x) {
    this.x = x;
    return this;
  }

   /**
   * x coordinate of the face point in pixels.
   * @return x
  **/
  @ApiModelProperty(value = "x coordinate of the face point in pixels.")
  public Double getX() {
    return x;
  }

  public void setX(Double x) {
    this.x = x;
  }

  public Point y(Double y) {
    this.y = y;
    return this;
  }

   /**
   * y coordinate of the face point in pixels.
   * @return y
  **/
  @ApiModelProperty(value = "y coordinate of the face point in pixels.")
  public Double getY() {
    return y;
  }

  public void setY(Double y) {
    this.y = y;
  }

  public Point type(Integer type) {
    this.type = type;
    return this;
  }

   /**
   * numerical face point unique type identifier.
   * @return type
  **/
  @ApiModelProperty(value = "numerical face point unique type identifier.")
  public Integer getType() {
    return type;
  }

  public void setType(Integer type) {
    this.type = type;
  }

  public Point name(String name) {
    this.name = name;
    return this;
  }

   /**
   * face point type name for display.
   * @return name
  **/
  @ApiModelProperty(value = "face point type name for display.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Point point = (Point) o;
    return Objects.equals(this.x, point.x) &&
        Objects.equals(this.y, point.y) &&
        Objects.equals(this.type, point.type) &&
        Objects.equals(this.name, point.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(x, y, type, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Point {\n");
    
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

