/*
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * represents a recognition request for one or more faces.
 */
@ApiModel(description = "represents a recognition request for one or more faces.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-02T11:12:16.872Z")
public class RecognizeRequest {
  @SerializedName("api_key")
  private UUID apiKey = null;

  @SerializedName("faces_uuids")
  private List<UUID> facesUuids = new ArrayList<UUID>();

  @SerializedName("targets")
  private List<String> targets = new ArrayList<String>();

  @SerializedName("parameters")
  private String parameters = null;

  public RecognizeRequest apiKey(UUID apiKey) {
    this.apiKey = apiKey;
    return this;
  }

   /**
   * your API key or d45fd466-51e2-4701-8da8-04351c872236
   * @return apiKey
  **/
  @ApiModelProperty(required = true, value = "your API key or d45fd466-51e2-4701-8da8-04351c872236")
  public UUID getApiKey() {
    return apiKey;
  }

  public void setApiKey(UUID apiKey) {
    this.apiKey = apiKey;
  }

  public RecognizeRequest facesUuids(List<UUID> facesUuids) {
    this.facesUuids = facesUuids;
    return this;
  }

  public RecognizeRequest addFacesUuidsItem(UUID facesUuidsItem) {
    this.facesUuids.add(facesUuidsItem);
    return this;
  }

   /**
   * list of face unique identifiers that should be recognized.
   * @return facesUuids
  **/
  @ApiModelProperty(required = true, value = "list of face unique identifiers that should be recognized.")
  public List<UUID> getFacesUuids() {
    return facesUuids;
  }

  public void setFacesUuids(List<UUID> facesUuids) {
    this.facesUuids = facesUuids;
  }

  public RecognizeRequest targets(List<String> targets) {
    this.targets = targets;
    return this;
  }

  public RecognizeRequest addTargetsItem(String targetsItem) {
    this.targets.add(targetsItem);
    return this;
  }

   /**
   * list of recognition targets which can include face identifiers, fully qualified person ids in format name@namespace or entire namespaces in format all@namespace.
   * @return targets
  **/
  @ApiModelProperty(required = true, value = "list of recognition targets which can include face identifiers, fully qualified person ids in format name@namespace or entire namespaces in format all@namespace.")
  public List<String> getTargets() {
    return targets;
  }

  public void setTargets(List<String> targets) {
    this.targets = targets;
  }

  public RecognizeRequest parameters(String parameters) {
    this.parameters = parameters;
    return this;
  }

   /**
   * (optional) comma separated list of recognition parameters, currently supported min_match_score (minimum recognition score), min_score (minimum detection score), gender and race filter.  for example: \&quot;min_match_score:0.4,min_score:0.2,gender:male,race:white\&quot;
   * @return parameters
  **/
  @ApiModelProperty(value = "(optional) comma separated list of recognition parameters, currently supported min_match_score (minimum recognition score), min_score (minimum detection score), gender and race filter.  for example: \"min_match_score:0.4,min_score:0.2,gender:male,race:white\"")
  public String getParameters() {
    return parameters;
  }

  public void setParameters(String parameters) {
    this.parameters = parameters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecognizeRequest recognizeRequest = (RecognizeRequest) o;
    return Objects.equals(this.apiKey, recognizeRequest.apiKey) &&
        Objects.equals(this.facesUuids, recognizeRequest.facesUuids) &&
        Objects.equals(this.targets, recognizeRequest.targets) &&
        Objects.equals(this.parameters, recognizeRequest.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiKey, facesUuids, targets, parameters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecognizeRequest {\n");
    
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    facesUuids: ").append(toIndentedString(facesUuids)).append("\n");
    sb.append("    targets: ").append(toIndentedString(targets)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

