/*
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Match;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * represents a recognition result for a single face.
 */
@ApiModel(description = "represents a recognition result for a single face.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-02T11:12:16.872Z")
public class RecognizeResult {
  @SerializedName("face_uuid")
  private UUID faceUuid = null;

  @SerializedName("matches")
  private List<Match> matches = null;

  public RecognizeResult faceUuid(UUID faceUuid) {
    this.faceUuid = faceUuid;
    return this;
  }

   /**
   * face unique identifier.
   * @return faceUuid
  **/
  @ApiModelProperty(value = "face unique identifier.")
  public UUID getFaceUuid() {
    return faceUuid;
  }

  public void setFaceUuid(UUID faceUuid) {
    this.faceUuid = faceUuid;
  }

  public RecognizeResult matches(List<Match> matches) {
    this.matches = matches;
    return this;
  }

  public RecognizeResult addMatchesItem(Match matchesItem) {
    if (this.matches == null) {
      this.matches = new ArrayList<Match>();
    }
    this.matches.add(matchesItem);
    return this;
  }

   /**
   * list of closest matches sorted by recognition score in descending order.
   * @return matches
  **/
  @ApiModelProperty(value = "list of closest matches sorted by recognition score in descending order.")
  public List<Match> getMatches() {
    return matches;
  }

  public void setMatches(List<Match> matches) {
    this.matches = matches;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecognizeResult recognizeResult = (RecognizeResult) o;
    return Objects.equals(this.faceUuid, recognizeResult.faceUuid) &&
        Objects.equals(this.matches, recognizeResult.matches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(faceUuid, matches);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecognizeResult {\n");
    
    sb.append("    faceUuid: ").append(toIndentedString(faceUuid)).append("\n");
    sb.append("    matches: ").append(toIndentedString(matches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

