/*
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.RecognizeResult;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * represents a recognition results for one or more faces.
 */
@ApiModel(description = "represents a recognition results for one or more faces.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-02T11:12:16.872Z")
public class Recognize {
  @SerializedName("recognize_uuid")
  private UUID recognizeUuid = null;

  @SerializedName("results")
  private List<RecognizeResult> results = null;

  public Recognize recognizeUuid(UUID recognizeUuid) {
    this.recognizeUuid = recognizeUuid;
    return this;
  }

   /**
   * recognize request unique identifier.
   * @return recognizeUuid
  **/
  @ApiModelProperty(value = "recognize request unique identifier.")
  public UUID getRecognizeUuid() {
    return recognizeUuid;
  }

  public void setRecognizeUuid(UUID recognizeUuid) {
    this.recognizeUuid = recognizeUuid;
  }

  public Recognize results(List<RecognizeResult> results) {
    this.results = results;
    return this;
  }

  public Recognize addResultsItem(RecognizeResult resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<RecognizeResult>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * collection of recognize results.
   * @return results
  **/
  @ApiModelProperty(value = "collection of recognize results.")
  public List<RecognizeResult> getResults() {
    return results;
  }

  public void setResults(List<RecognizeResult> results) {
    this.results = results;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Recognize recognize = (Recognize) o;
    return Objects.equals(this.recognizeUuid, recognize.recognizeUuid) &&
        Objects.equals(this.results, recognize.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recognizeUuid, results);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Recognize {\n");
    
    sb.append("    recognizeUuid: ").append(toIndentedString(recognizeUuid)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

