/*
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * represents a set person call body parameters.
 */
@ApiModel(description = "represents a set person call body parameters.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-02T11:12:16.872Z")
public class SetPerson {
  @SerializedName("api_key")
  private UUID apiKey = null;

  @SerializedName("faces_uuids")
  private List<UUID> facesUuids = new ArrayList<UUID>();

  @SerializedName("person_id")
  private String personId = null;

  public SetPerson apiKey(UUID apiKey) {
    this.apiKey = apiKey;
    return this;
  }

   /**
   * your API key or d45fd466-51e2-4701-8da8-04351c872236
   * @return apiKey
  **/
  @ApiModelProperty(required = true, value = "your API key or d45fd466-51e2-4701-8da8-04351c872236")
  public UUID getApiKey() {
    return apiKey;
  }

  public void setApiKey(UUID apiKey) {
    this.apiKey = apiKey;
  }

  public SetPerson facesUuids(List<UUID> facesUuids) {
    this.facesUuids = facesUuids;
    return this;
  }

  public SetPerson addFacesUuidsItem(UUID facesUuidsItem) {
    this.facesUuids.add(facesUuidsItem);
    return this;
  }

   /**
   * list of face uuids to set person id. each face can have only one person id assigned to it. setting a person id overwrites the old value.
   * @return facesUuids
  **/
  @ApiModelProperty(required = true, value = "list of face uuids to set person id. each face can have only one person id assigned to it. setting a person id overwrites the old value.")
  public List<UUID> getFacesUuids() {
    return facesUuids;
  }

  public void setFacesUuids(List<UUID> facesUuids) {
    this.facesUuids = facesUuids;
  }

  public SetPerson personId(String personId) {
    this.personId = personId;
    return this;
  }

   /**
   * person id in format name@namespace. name and namespace can include letters, numbers, dots, underscores and spaces. special name random@namespace could be used to assign random person name with specific namespace. Namespace part should not exceed 60 characters. Name part should not exceed 200 characters. Setting person_id to empty string resets the person id. Faces will be permanently stored for as long as person id is assigned to them. Faces without person ids will be deleted starting from 24 hours. Resetting person id on faces generated more than 24 hours ago may immediately delete the. When face is assigned to/removed from namespace search indexes of namespaces involved will asynchrously update. It may take from seconds to serveral minutes depending on namespace size for changes to propagate.
   * @return personId
  **/
  @ApiModelProperty(value = "person id in format name@namespace. name and namespace can include letters, numbers, dots, underscores and spaces. special name random@namespace could be used to assign random person name with specific namespace. Namespace part should not exceed 60 characters. Name part should not exceed 200 characters. Setting person_id to empty string resets the person id. Faces will be permanently stored for as long as person id is assigned to them. Faces without person ids will be deleted starting from 24 hours. Resetting person id on faces generated more than 24 hours ago may immediately delete the. When face is assigned to/removed from namespace search indexes of namespaces involved will asynchrously update. It may take from seconds to serveral minutes depending on namespace size for changes to propagate.")
  public String getPersonId() {
    return personId;
  }

  public void setPersonId(String personId) {
    this.personId = personId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetPerson setPerson = (SetPerson) o;
    return Objects.equals(this.apiKey, setPerson.apiKey) &&
        Objects.equals(this.facesUuids, setPerson.facesUuids) &&
        Objects.equals(this.personId, setPerson.personId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiKey, facesUuids, personId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetPerson {\n");
    
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    facesUuids: ").append(toIndentedString(facesUuids)).append("\n");
    sb.append("    personId: ").append(toIndentedString(personId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

