/*
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * represents a media or object tag.
 */
@ApiModel(description = "represents a media or object tag.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-02T11:12:16.872Z")
public class TagMedia {
  @SerializedName("name")
  private String name = null;

  @SerializedName("value")
  private String value = null;

  @SerializedName("confidence")
  private Double confidence = null;

  @SerializedName("x")
  private Double x = null;

  @SerializedName("y")
  private Double y = null;

  @SerializedName("width")
  private Double width = null;

  @SerializedName("height")
  private Double height = null;

  @SerializedName("angle")
  private Double angle = null;

  @SerializedName("instance_id")
  private Integer instanceId = null;

  @SerializedName("start")
  private String start = null;

  @SerializedName("duration")
  private String duration = null;

  public TagMedia name(String name) {
    this.name = name;
    return this;
  }

   /**
   * tag name.
   * @return name
  **/
  @ApiModelProperty(value = "tag name.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TagMedia value(String value) {
    this.value = value;
    return this;
  }

   /**
   * tag value.
   * @return value
  **/
  @ApiModelProperty(value = "tag value.")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public TagMedia confidence(Double confidence) {
    this.confidence = confidence;
    return this;
  }

   /**
   * tag confidence, if automatically detected, otherwise 1.0.
   * @return confidence
  **/
  @ApiModelProperty(value = "tag confidence, if automatically detected, otherwise 1.0.")
  public Double getConfidence() {
    return confidence;
  }

  public void setConfidence(Double confidence) {
    this.confidence = confidence;
  }

  public TagMedia x(Double x) {
    this.x = x;
    return this;
  }

   /**
   * reserved for future use
   * @return x
  **/
  @ApiModelProperty(value = "reserved for future use")
  public Double getX() {
    return x;
  }

  public void setX(Double x) {
    this.x = x;
  }

  public TagMedia y(Double y) {
    this.y = y;
    return this;
  }

   /**
   * reserved for future use
   * @return y
  **/
  @ApiModelProperty(value = "reserved for future use")
  public Double getY() {
    return y;
  }

  public void setY(Double y) {
    this.y = y;
  }

  public TagMedia width(Double width) {
    this.width = width;
    return this;
  }

   /**
   * reserved for future use
   * @return width
  **/
  @ApiModelProperty(value = "reserved for future use")
  public Double getWidth() {
    return width;
  }

  public void setWidth(Double width) {
    this.width = width;
  }

  public TagMedia height(Double height) {
    this.height = height;
    return this;
  }

   /**
   * reserved for future use
   * @return height
  **/
  @ApiModelProperty(value = "reserved for future use")
  public Double getHeight() {
    return height;
  }

  public void setHeight(Double height) {
    this.height = height;
  }

  public TagMedia angle(Double angle) {
    this.angle = angle;
    return this;
  }

   /**
   * reserved for future use
   * @return angle
  **/
  @ApiModelProperty(value = "reserved for future use")
  public Double getAngle() {
    return angle;
  }

  public void setAngle(Double angle) {
    this.angle = angle;
  }

  public TagMedia instanceId(Integer instanceId) {
    this.instanceId = instanceId;
    return this;
  }

   /**
   * reserved for future use
   * @return instanceId
  **/
  @ApiModelProperty(value = "reserved for future use")
  public Integer getInstanceId() {
    return instanceId;
  }

  public void setInstanceId(Integer instanceId) {
    this.instanceId = instanceId;
  }

  public TagMedia start(String start) {
    this.start = start;
    return this;
  }

   /**
   * reserved for future video processing
   * @return start
  **/
  @ApiModelProperty(value = "reserved for future video processing")
  public String getStart() {
    return start;
  }

  public void setStart(String start) {
    this.start = start;
  }

  public TagMedia duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * reserved for future video processing
   * @return duration
  **/
  @ApiModelProperty(value = "reserved for future video processing")
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TagMedia tagMedia = (TagMedia) o;
    return Objects.equals(this.name, tagMedia.name) &&
        Objects.equals(this.value, tagMedia.value) &&
        Objects.equals(this.confidence, tagMedia.confidence) &&
        Objects.equals(this.x, tagMedia.x) &&
        Objects.equals(this.y, tagMedia.y) &&
        Objects.equals(this.width, tagMedia.width) &&
        Objects.equals(this.height, tagMedia.height) &&
        Objects.equals(this.angle, tagMedia.angle) &&
        Objects.equals(this.instanceId, tagMedia.instanceId) &&
        Objects.equals(this.start, tagMedia.start) &&
        Objects.equals(this.duration, tagMedia.duration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, value, confidence, x, y, width, height, angle, instanceId, start, duration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TagMedia {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    angle: ").append(toIndentedString(angle)).append("\n");
    sb.append("    instanceId: ").append(toIndentedString(instanceId)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

