/*
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * represents a daily api usage information.
 */
@ApiModel(description = "represents a daily api usage information.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-02T11:12:16.872Z")
public class UsageDaily {
  @SerializedName("year")
  private Integer year = null;

  @SerializedName("month")
  private Integer month = null;

  @SerializedName("day")
  private Integer day = null;

  @SerializedName("images")
  private Integer images = null;

  public UsageDaily year(Integer year) {
    this.year = year;
    return this;
  }

   /**
   * year
   * @return year
  **/
  @ApiModelProperty(value = "year")
  public Integer getYear() {
    return year;
  }

  public void setYear(Integer year) {
    this.year = year;
  }

  public UsageDaily month(Integer month) {
    this.month = month;
    return this;
  }

   /**
   * month
   * @return month
  **/
  @ApiModelProperty(value = "month")
  public Integer getMonth() {
    return month;
  }

  public void setMonth(Integer month) {
    this.month = month;
  }

  public UsageDaily day(Integer day) {
    this.day = day;
    return this;
  }

   /**
   * day
   * @return day
  **/
  @ApiModelProperty(value = "day")
  public Integer getDay() {
    return day;
  }

  public void setDay(Integer day) {
    this.day = day;
  }

  public UsageDaily images(Integer images) {
    this.images = images;
    return this;
  }

   /**
   * processed images count
   * @return images
  **/
  @ApiModelProperty(value = "processed images count")
  public Integer getImages() {
    return images;
  }

  public void setImages(Integer images) {
    this.images = images;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageDaily usageDaily = (UsageDaily) o;
    return Objects.equals(this.year, usageDaily.year) &&
        Objects.equals(this.month, usageDaily.month) &&
        Objects.equals(this.day, usageDaily.day) &&
        Objects.equals(this.images, usageDaily.images);
  }

  @Override
  public int hashCode() {
    return Objects.hash(year, month, day, images);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageDaily {\n");
    
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

