/*
 * Betaface API 2.0
 * Betaface face recognition API.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.CroppedFace;
import io.swagger.client.model.Error;
import io.swagger.client.model.Face;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class FaceApi {
    private ApiClient apiClient;

    public FaceApi() {
        this(Configuration.getDefaultApiClient());
    }

    public FaceApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for v2FaceCroppedGet
     * @param apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236 (required)
     * @param faceUuid the requested media identifier. (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call v2FaceCroppedGetCall(UUID apiKey, UUID faceUuid, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/face/cropped";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (apiKey != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("api_key", apiKey));
        if (faceUuid != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("face_uuid", faceUuid));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call v2FaceCroppedGetValidateBeforeCall(UUID apiKey, UUID faceUuid, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'apiKey' is set
        if (apiKey == null) {
            throw new ApiException("Missing the required parameter 'apiKey' when calling v2FaceCroppedGet(Async)");
        }
        
        // verify the required parameter 'faceUuid' is set
        if (faceUuid == null) {
            throw new ApiException("Missing the required parameter 'faceUuid' when calling v2FaceCroppedGet(Async)");
        }
        

        com.squareup.okhttp.Call call = v2FaceCroppedGetCall(apiKey, faceUuid, progressListener, progressRequestListener);
        return call;

    }

    /**
     * gets a single cropped face information including cropped face image.
     * 
     * @param apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236 (required)
     * @param faceUuid the requested media identifier. (required)
     * @return CroppedFace
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public CroppedFace v2FaceCroppedGet(UUID apiKey, UUID faceUuid) throws ApiException {
        ApiResponse<CroppedFace> resp = v2FaceCroppedGetWithHttpInfo(apiKey, faceUuid);
        return resp.getData();
    }

    /**
     * gets a single cropped face information including cropped face image.
     * 
     * @param apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236 (required)
     * @param faceUuid the requested media identifier. (required)
     * @return ApiResponse&lt;CroppedFace&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<CroppedFace> v2FaceCroppedGetWithHttpInfo(UUID apiKey, UUID faceUuid) throws ApiException {
        com.squareup.okhttp.Call call = v2FaceCroppedGetValidateBeforeCall(apiKey, faceUuid, null, null);
        Type localVarReturnType = new TypeToken<CroppedFace>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * gets a single cropped face information including cropped face image. (asynchronously)
     * 
     * @param apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236 (required)
     * @param faceUuid the requested media identifier. (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call v2FaceCroppedGetAsync(UUID apiKey, UUID faceUuid, final ApiCallback<CroppedFace> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = v2FaceCroppedGetValidateBeforeCall(apiKey, faceUuid, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<CroppedFace>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for v2FaceGet
     * @param apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236 (required)
     * @param faceUuid the requested media identifier. (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call v2FaceGetCall(UUID apiKey, UUID faceUuid, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v2/face";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (apiKey != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("api_key", apiKey));
        if (faceUuid != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("face_uuid", faceUuid));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call v2FaceGetValidateBeforeCall(UUID apiKey, UUID faceUuid, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'apiKey' is set
        if (apiKey == null) {
            throw new ApiException("Missing the required parameter 'apiKey' when calling v2FaceGet(Async)");
        }
        
        // verify the required parameter 'faceUuid' is set
        if (faceUuid == null) {
            throw new ApiException("Missing the required parameter 'faceUuid' when calling v2FaceGet(Async)");
        }
        

        com.squareup.okhttp.Call call = v2FaceGetCall(apiKey, faceUuid, progressListener, progressRequestListener);
        return call;

    }

    /**
     * gets a single face information.
     * 
     * @param apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236 (required)
     * @param faceUuid the requested media identifier. (required)
     * @return Face
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public Face v2FaceGet(UUID apiKey, UUID faceUuid) throws ApiException {
        ApiResponse<Face> resp = v2FaceGetWithHttpInfo(apiKey, faceUuid);
        return resp.getData();
    }

    /**
     * gets a single face information.
     * 
     * @param apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236 (required)
     * @param faceUuid the requested media identifier. (required)
     * @return ApiResponse&lt;Face&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Face> v2FaceGetWithHttpInfo(UUID apiKey, UUID faceUuid) throws ApiException {
        com.squareup.okhttp.Call call = v2FaceGetValidateBeforeCall(apiKey, faceUuid, null, null);
        Type localVarReturnType = new TypeToken<Face>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * gets a single face information. (asynchronously)
     * 
     * @param apiKey your API key or d45fd466-51e2-4701-8da8-04351c872236 (required)
     * @param faceUuid the requested media identifier. (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call v2FaceGetAsync(UUID apiKey, UUID faceUuid, final ApiCallback<Face> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = v2FaceGetValidateBeforeCall(apiKey, faceUuid, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<Face>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
